name: Comprobar enlaces rotos

on:
  schedule:
    - cron: "0 5 * * 1"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  check-links:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v4

      - name: Comprobar enlaces rotos
        uses: lycheeverse/lychee-action@v1
        with:
          args: >
            --verbose
            --no-progress
            './**/*.html'
            './**/*.md'
